
DECLARE
  CURSOR cursor_1 IS
    SELECT TABLE_NAME
    FROM DICT_COLUMNS
    WHERE COLUMN_NAME = 'BLOCKS'
      AND TABLE_NAME LIKE 'USER%'
      ORDER BY TABLE_NAME DESC;
 rec_1 cursor_1%ROWTYPE;
BEGIN
  FOR rec_1 IN cursor_1 LOOP
  DBMS_OUTPUT.PUT_LINE(rec_1.TABLE_NAME);
  END LOOP;
END;